start-at-login = true

after-login-command = []

after-startup-command = [
#'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color=0xFFFFBE69 inactive_color=0xFF007692 width=8.0'
]

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

[gaps]
#outer.bottom numbers have to match presentation.sh variables. built-in retina display is excluded from presentation mode, so this only works on external monitors.
outer.bottom =     [{monitor.'^built-in retina display$' = 20 }, 40]
outer.top =        [{monitor.'^built-in retina display$' = 30 }, 82]
outer.left =       40
outer.right =      40
inner.horizontal = 40
inner.vertical =   40

[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section,
[exec.env-vars]          # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]
cmd-space = 'layout floating tiling'
cmd-r = ['mode resize']
cmd-keypadMinus = 'resize smart -70'
cmd-keypadPlus = 'resize smart +70'
cmd-g = ['mode join']
cmd-q = ['close --quit-if-last-window']
#cmd-w = []

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

cmd-enter = 'exec-and-forget open -n /Volumes/Macintosh\ HD/Applications/Ghostty.app'

#cmd-shift-f = 'macos-native-fullscreen'
cmd-shift-f = 'fullscreen'

alt-g = 'split horizontal'
alt-v = 'split vertical'

cmd-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop left'
cmd-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
cmd-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
cmd-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop right'
cmd-left = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop left'
cmd-down = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
cmd-up = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
cmd-right = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop right'

cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'
cmd-shift-left = 'move left'
cmd-shift-down = 'move down'
cmd-shift-up = 'move up'
cmd-shift-right = 'move right'

cmd-1 = 'workspace --auto-back-and-forth 1'
cmd-2 = 'workspace --auto-back-and-forth 2'
cmd-3 = 'workspace --auto-back-and-forth 3'
cmd-4 = 'workspace --auto-back-and-forth 4'
cmd-5 = 'workspace --auto-back-and-forth 5'
cmd-6 = 'workspace --auto-back-and-forth 6'
cmd-7 = 'workspace --auto-back-and-forth 7'
cmd-8 = 'workspace --auto-back-and-forth 8'
cmd-9 = 'workspace --auto-back-and-forth 9'

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'

cmd-tab = 'workspace-back-and-forth'
# cmd-p = 'move-workspace-to-monitor --wrap-around next'
# cmd-shift-p = [
#   'move-node-to-monitor --wrap-around next',
#   'focus-monitor next --wrap-around'
# ]
# cmd-alt-h = []

cmd-shift-s = ['mode service']

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2

s = [
  'exec-and-forget cat ~/.config/aerospace/shrugstring| pbcopy',
  'mode main'
]

b = [
  'exec-and-forget ~/.config/aerospace/presentation.sh on',
  'mode main'
]
shift-b = [
   'exec-and-forget ~/.config/aerospace/presentation.sh off',
   'mode main'
]

backspace = ['close-all-windows-but-current', 'mode main']

[mode.resize.binding]
keypadMinus = 'resize smart -70'
keypadPlus = 'resize smart +70'
h = ['resize width -64']
j = ['resize height -64']
k = ['resize height +64']
l = ['resize width +64']
esc = ['mode main']
enter = ['mode main']

[mode.join.binding]
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']
cmd-h = ['join-with left', 'mode main']
cmd-alt-h = ['join-with left', 'mode main']
esc = ['mode main']
enter = ['mode main']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating', 'move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.app-id = 'it.bloop.airmail2'
run = ['move-node-to-workspace 7']

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['move-node-to-workspace 8']

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = ['layout floating', 'move-node-to-workspace 9']

