# AEROSPACE CONFIG
start-at-login = true

after-login-command = []

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

on-focused-monitor-changed = [
  'move-mouse monitor-lazy-center'
]

on-focus-changed = [
  'move-mouse window-lazy-center',
  'exec-and-forget /bin/bash -c /opt/homebrew/bin/sketchybar --trigger front_app_switched',
  'exec-and-forget sketchybar --trigger update_windows'
]

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
outer.bottom =     10
outer.top =        10
outer.left =       10
outer.right =      10
inner.horizontal = 10
inner.vertical =   10

[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section,
[exec.env-vars]          # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]
cmd-space = 'layout floating tiling'
# cmd-r = [
#   'mode resize',
#   'exec-and-forget sketchybar --trigger send_message MESSAGE="RESIZE MODE" HOLD="true"'
# ]

cmd-g = [
  'mode join',
  'exec-and-forget sketchybar --trigger send_message MESSAGE="JOIN MODE" HOLD="true"'
]

cmd-q = [
  'close --quit-if-last-window'
]
#cmd-w = []

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

cmd-enter = 'exec-and-forget ~/.config/aerospace/new_ghostty.sh'

#cmd-shift-f = 'macos-native-fullscreen'
cmd-shift-f = 'fullscreen'

alt-g = 'split horizontal'
alt-v = 'split vertical'

# cmd-left = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop left'
# cmd-down = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
# cmd-up = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
# cmd-right = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop right'

cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'
cmd-shift-left = 'move left'
cmd-shift-down = 'move down'
cmd-shift-up = 'move up'
cmd-shift-right = 'move right'

cmd-1 = 'workspace --auto-back-and-forth 1'  # Notes
cmd-2 = 'workspace --auto-back-and-forth 2'  # Terminal
cmd-3 = 'workspace --auto-back-and-forth 3'  # Browser
cmd-4 = 'workspace --auto-back-and-forth 4'  # AltBrowser
cmd-5 = 'workspace --auto-back-and-forth 5'  # AltBrowser
cmd-6 = 'workspace --auto-back-and-forth 6'  # AltBrowser

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'

cmd-tab = 'workspace-back-and-forth'
# cmd-p = 'move-workspace-to-monitor --wrap-around next'
# cmd-shift-p = [
#   'move-node-to-monitor --wrap-around next',
#   'focus-monitor next --wrap-around' 
# ]
cmd-alt-h = []

cmd-shift-s = [
  'mode service',
  'exec-and-forget sketchybar --trigger send_message MESSAGE="SERVICE MODE" HOLD="true"'
]

[mode.service.binding]
esc = [
  'reload-config',
  'exec-and-forget sketchybar --trigger hide_message',
  'exec-and-forget sketchybar --reload',
  'mode main'
]
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2

s = [
  'exec-and-forget cat ~/.config/aerospace/shrugstring| pbcopy',
  'exec-and-forget sketchybar --trigger hide_message',
  'mode main'
] 

# b = [
#   'exec-and-forget ~/.config/aerospace/presentation.sh on',
#   'exec-and-forget sketchybar --bar height=0',
#   'exec-and-forget sketchybar --trigger hide_message',
#   'mode main'
# ]
# shift-b = [
#   'exec-and-forget ~/.config/aerospace/presentation.sh off',
#   'exec-and-forget sketchybar --bar height=36',
#   'exec-and-forget sketchybar --trigger hide_message',
#   'mode main'
# ]

backspace = ['close-all-windows-but-current', 'mode main']

[mode.resize.binding]
keypadMinus = 'resize smart -70'
keypadPlus = 'resize smart +70'
h = ['resize width -64']
j = ['resize height -64']
k = ['resize height +64']
l = ['resize width +64']
esc = [
  'mode main',
  'exec-and-forget sketchybar --trigger hide_message'
]
enter = [
  'mode main',
  'exec-and-forget sketchybar --trigger hide_message'
]

[mode.join.binding]
h = ['join-with left', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
j = ['join-with down', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
k = ['join-with up', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
l = ['join-with right', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
cmd-h = ['join-with left', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
cmd-alt-h = ['join-with left', 'mode main', 'exec-and-forget sketchybar --trigger hide_message']
esc = [
  'mode main',
  'exec-and-forget sketchybar --trigger hide_message'
]
enter = [
  'mode main',
  'exec-and-forget sketchybar --trigger hide_message'
]

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.vivaldi.Vivaldi'
run = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout tiling', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['layout tiling', 'move-node-to-workspace 4']
